name: Scala CI

# Run this workflow on push and pull request events
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the source code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Cache SBT dependencies
      - name: Cache SBT dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      # Step 4: Install sbt (Scala Build Tool)
      - name: Install sbt
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
          sudo apt-get update
          sudo apt-get install sbt

      # Step 5: Verify SBT version
      - name: Check SBT version
        run: sbt --version

      # Step 6: Compile the Scala project
      - name: Compile project
        run: sbt compile

      # Step 7: Run tests
      - name: Run tests
        run: |
          set -e  # Stop the build on any error
          sbt test

      # Step 8: Archive test results for review
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-reports/